import { useState } from "react";
import { UniversityCard } from "@/components/UniversityCard";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";

export interface University {
  id: number;
  name: string;
  location: string;
  city: string;
  tuitionFee: number;
  currency: string;
  facilities: string[];
  description: string;
  features: string[];
  image: string;
  country: string;
  rating: number;
  category: string;
  duration?: string;
  medium?: string;
}

export const universities: University[] = [
  // Russia
  {
    id: 1,
    name: "Altai State Medical University",
    country: "russia",
    location: "Russia",
    city: "Barnaul",
    tuitionFee: 5000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/ALTAI.jpg",
    description: "A well-known medical university in Russia.",
    features: ["Affordable", "English medium", "Recognized by WHO"],
    facilities: ["Library", "Hostel"],
    rating: 4.5,
    category: "Medical",
  },

  // Russia
  {
    id: 2,
    name: "Bashkir State Medical University",
    country: "russia",
    location: "Russia",
    city: "Ufa",
    tuitionFee: 4800,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/BASHKIR.jpg",
    description: "A top-rated medical university located in Ufa.",
    features: ["Recognized by WHO", "Affordable fees"],
    facilities: ["Library", "Hostel"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 3,
    name: "Mari State University",
    country: "russia",
    location: "Russia",
    city: "Yoshkar-Ola",
    tuitionFee: 4700,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/MARI.jpg",
    description: "Popular among Indian students pursuing MBBS.",
    features: ["WHO recognition", "English medium"],
    facilities: ["Library", "Hostel"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 4,
    name: "Syktyvkar State University",
    country: "russia",
    location: "Russia",
    city: "Syktyvkar",
    tuitionFee: 4500,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/SYKTYVKAR.jpg",
    description: "Renowned for medical and technical education.",
    features: ["Low cost", "Modern labs"],
    facilities: ["Library", "Cafeteria"],
    rating: 4.1,
    category: "Medical",
  },
  {
    id: 5,
    name: "V.I Vernadsky Crimean Federal University",
    country: "russia",
    location: "Russia",
    city: "Simferopol",
    tuitionFee: 5000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/VERNADSKY.jpg",
    description: "One of the leading federal universities in Crimea.",
    features: ["WHO/NMC approved", "Modern campus"],
    facilities: ["Library", "Gym", "Hostel"],
    rating: 4.4,
    category: "Medical",
  },
  {
    id: 6,
    name: "Orel State Medical University",
    country: "russia",
    location: "Russia",
    city: "Orel",
    tuitionFee: 4600,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/OREL.jpg",
    description: "Affordable and quality education for international students.",
    features: ["Recognized globally", "Affordable"],
    facilities: ["Library", "Sports Complex"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 7,
    name: "South Ural State Medical University",
    country: "russia",
    location: "Russia",
    city: "Chelyabinsk",
    tuitionFee: 4800,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/SOUTHURAL.jpg",
    description: "Modern infrastructure and globally recognized curriculum.",
    features: ["English medium", "Research oriented"],
    facilities: ["Library", "Labs", "Hostel"],
    rating: 4.5,
    category: "Medical",
  },
  {
    id: 8,
    name: "Tver State Medical University",
    country: "russia",
    location: "Russia",
    city: "Tver",
    tuitionFee: 4700,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/TVERSM.jpg",
    description: "Well-established university with English programs.",
    features: ["WHO listed", "Clinical exposure"],
    facilities: ["Library", "Hospital"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 9,
    name: "Kabardino Balkarian State University",
    country: "russia",
    location: "Russia",
    city: "Nalchik",
    tuitionFee: 4500,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/KABARDINO.jpg",
    description: "Offers a variety of programs including MBBS.",
    features: ["Affordable", "Recognized by NMC"],
    facilities: ["Library", "Labs"],
    rating: 4.1,
    category: "Medical",
  },
  {
    id: 10,
    name: "Ulyanovsk State University",
    country: "russia",
    location: "Russia",
    city: "Ulyanovsk",
    tuitionFee: 4600,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/ULYANOVSK.jpg",
    description: "High reputation in research and clinical training.",
    features: ["Low cost", "English curriculum"],
    facilities: ["Library", "Sports Facilities"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 11,
    name: "Orenburg State Medical University",
    country: "russia",
    location: "Russia",
    city: "Orenburg",
    tuitionFee: 4700,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/RUSSIA/ORENBURG.jpg",
    description: "Well-established Russian MBBS destination.",
    features: ["Top FMGE results", "Affordable"],
    facilities: ["Library", "Canteen", "Hostel"],
    rating: 4.3,
    category: "Medical",
  },

  // Georgia
  {
    id: 12,
    name: "Batumi Shote Rustaveli State University",
    country: "georgia",
    location: "Georgia",
    city: "Batumi",
    tuitionFee: 5000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/GEORGIA/BATUMI.jpg",
    description: "Public university known for modern MBBS education.",
    features: ["WHO approved", "English medium", "Affordable"],
    facilities: ["Library", "Hostel", "Labs"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 13,
    name: "Caucasus International University",
    country: "georgia",
    location: "Georgia",
    city: "Tbilisi",
    tuitionFee: 5200,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/GEORGIA/CAUCASUS.jpeg",
    description: "Private medical university with modern facilities.",
    features: ["English taught", "Highly rated", "International students"],
    facilities: ["Library", "Sports Center", "Hostel"],
    rating: 4.4,
    category: "Medical",
  },
  {
    id: 14,
    name: "European University",
    country: "georgia",
    location: "Georgia",
    city: "Tbilisi",
    tuitionFee: 5500,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/GEORGIA/EUROPEAN.jpg",
    description: "Modern medical university with European standards of education.",
    features: ["European standards", "Modern facilities", "International faculty"],
    facilities: ["Library", "Labs", "Hostel", "Sports Complex"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 15,
    name: "Georgian National University (SEU)",
    country: "georgia",
    location: "Georgia",
    city: "Tbilisi",
    tuitionFee: 5300,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/GEORGIA/SEU.jpg",
    description: "Leading private university offering quality medical education.",
    features: ["WHO recognized", "Modern campus", "Clinical training"],
    facilities: ["Library", "Research Center", "Hostel"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 16,
    name: "Tbilisi State Medical University",
    country: "georgia",
    location: "Georgia",
    city: "Tbilisi",
    tuitionFee: 5800,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/GEORGIA/TBILISI.jpg",
    description: "One of the oldest and most prestigious medical universities in Georgia.",
    features: ["Historical prestige", "Research focus", "Clinical excellence"],
    facilities: ["Library", "Labs", "Hospital", "Research Centers"],
    rating: 4.5,
    category: "Medical",
  },

  // Philippines
  {
    id: 17,
    name: "Lyceum of the Philippines University",
    country: "philippines",
    location: "Philippines",
    city: "Manila",
    tuitionFee: 4000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/PHILIPPINES/LYCEUM.jpg",
    description: "Leading university known for quality medical education.",
    features: ["Affordable fees", "English medium", "Modern facilities"],
    facilities: ["Library", "Labs", "Hostel"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 18,
    name: "Davao Medical School Foundation",
    country: "philippines",
    location: "Philippines",
    city: "Davao",
    tuitionFee: 4200,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/PHILIPPINES/DAVAO.jpg",
    description: "Renowned medical school with excellent clinical exposure.",
    features: ["Clinical focus", "Research opportunities", "Modern campus"],
    facilities: ["Hospital", "Research Center", "Library"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 19,
    name: "Emilio Aguinaldo Medical Center",
    country: "philippines",
    location: "Philippines",
    city: "Cavite",
    tuitionFee: 4100,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/PHILIPPINES/EMILIO.jpeg",
    description: "Well-established medical center offering comprehensive education.",
    features: ["Hospital training", "Modern equipment", "Experienced faculty"],
    facilities: ["Medical Center", "Library", "Labs"],
    rating: 4.1,
    category: "Medical",
  },
  {
    id: 20,
    name: "Our Lady of Fatima University",
    country: "philippines",
    location: "Philippines",
    city: "Valenzuela",
    tuitionFee: 4300,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/PHILIPPINES/FATIMA.jpeg",
    description: "Leading medical university with strong clinical program.",
    features: ["Clinical excellence", "Modern facilities", "Research focus"],
    facilities: ["Hospital", "Library", "Research Labs"],
    rating: 4.4,
    category: "Medical",
  },
  {
    id: 21,
    name: "UV Gullas College of Medicine",
    country: "philippines",
    location: "Philippines",
    city: "Cebu",
    tuitionFee: 4000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/PHILIPPINES/UVGULLAS.png",
    description: "Established medical college with modern teaching methods.",
    features: ["Practical training", "Affordable", "Modern campus"],
    facilities: ["Labs", "Library", "Hospital"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 22,
    name: "University of Perpetual Help System",
    country: "philippines",
    location: "Philippines",
    city: "Las Piñas",
    tuitionFee: 4200,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/PHILIPPINES/PERPETUAL.jpeg",
    description: "Comprehensive medical education with modern facilities.",
    features: ["Quality education", "Clinical exposure", "Research opportunities"],
    facilities: ["Hospital", "Library", "Labs"],
    rating: 4.3,
    category: "Medical",
  },

  // Belarus
  {
    id: 23,
    name: "Belarusian State Medical University",
    country: "belarus",
    location: "Belarus",
    city: "Minsk",
    tuitionFee: 4800,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/BELARUS/BSMU.jpeg",
    description: "Premier medical university in Belarus with rich history.",
    features: ["Historical prestige", "Research excellence", "Clinical training"],
    facilities: ["Hospital", "Research Center", "Library"],
    rating: 4.5,
    category: "Medical",
  },
  {
    id: 24,
    name: "Grodno State Medical University",
    country: "belarus",
    location: "Belarus",
    city: "Grodno",
    tuitionFee: 4600,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/BELARUS/GRODNO.jpg",
    description: "Leading medical university known for quality education.",
    features: ["Modern facilities", "Clinical exposure", "Research focus"],
    facilities: ["Labs", "Hospital", "Library"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 25,
    name: "Vitebsk State Medical University",
    country: "belarus",
    location: "Belarus",
    city: "Vitebsk",
    tuitionFee: 4700,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/BELARUS/VITEBSK.jpg",
    description: "Renowned for medical education and research.",
    features: ["Research oriented", "Modern campus", "Clinical training"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.4,
    category: "Medical",
  },

  // Moldova
  {
    id: 26,
    name: "Nicolae Testemitanu State University of Medicine and Pharmacy",
    country: "moldova",
    location: "Moldova",
    city: "Chisinau",
    tuitionFee: 5000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/MOLDOVA/NICOLAE.png",
    description: "Leading medical university in Moldova with European standards.",
    features: ["European education", "Research focus", "Clinical excellence"],
    facilities: ["Hospital", "Research Labs", "Library"],
    rating: 4.4,
    category: "Medical",
  },
  // Bulgaria
  {
    id: 27,
    name: "Medical University Pleven",
    country: "bulgaria",
    location: "Bulgaria",
    city: "Pleven",
    tuitionFee: 5500,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/BULGARIA/PLEVEN.jpg",
    description: "Modern medical university with European standards.",
    features: ["EU recognized", "Modern facilities", "Clinical training"],
    facilities: ["Hospital", "Research Center", "Library"],
    rating: 4.3,
    category: "Medical",
  },

  // Bosnia
  {
    id: 28,
    name: "The University of East Sarajevo",
    country: "bosnia",
    location: "Bosnia",
    city: "East Sarajevo",
    tuitionFee: 5000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/BOSNIA/EASTSARAJEVO.jpg",
    description: "Leading medical university in Bosnia with modern facilities.",
    features: ["European standards", "Clinical exposure", "Research opportunities"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.2,
    category: "Medical",
  },

  // Uzbekistan
  {
    id: 29,
    name: "Andijan State Medical Institute",
    country: "uzbekistan",
    location: "Uzbekistan",
    city: "Andijan",
    tuitionFee: 4000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/UZBEKISTAN/ANDIJAN.jpg",
    description: "Well-established medical institute with modern facilities.",
    features: ["Affordable", "Quality education", "Clinical training"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.1,
    category: "Medical",
  },
  {
    id: 30,
    name: "Bukhara State Medical University",
    country: "uzbekistan",
    location: "Uzbekistan",
    city: "Bukhara",
    tuitionFee: 4200,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/UZBEKISTAN/BUKHARA.jpg",
    description: "Modern medical university with comprehensive programs.",
    features: ["Modern campus", "Research focus", "Clinical exposure"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 31,
    name: "Tashkent Medical Academy",
    country: "uzbekistan",
    location: "Uzbekistan",
    city: "Tashkent",
    tuitionFee: 4500,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/UZBEKISTAN/TASHKENT.jpg",
    description: "Premier medical academy in Uzbekistan.",
    features: ["Research excellence", "Modern facilities", "Clinical training"],
    facilities: ["Hospital", "Research Labs", "Library"],
    rating: 4.4,
    category: "Medical",
  },

  // Kazakhstan
  {
    id: 32,
    name: "Al-Farabi National University",
    country: "kazakhstan",
    location: "Kazakhstan",
    city: "Almaty",
    tuitionFee: 4800,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KAZAKHSTAN/ALFARABI.jpg",
    description: "Leading national university with strong medical program.",
    features: ["Research focus", "Modern campus", "Clinical excellence"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.4,
    category: "Medical",
  },
  {
    id: 33,
    name: "Astana Medical University",
    country: "kazakhstan",
    location: "Kazakhstan",
    city: "Astana",
    tuitionFee: 4600,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KAZAKHSTAN/ASTANA.jpg",
    description: "Modern medical university in the capital city.",
    features: ["Modern facilities", "Clinical training", "Research opportunities"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 34,
    name: "Caspian International School of Medicine",
    country: "kazakhstan",
    location: "Kazakhstan",
    city: "Aktau",
    tuitionFee: 4500,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KAZAKHSTAN/CASPIAN.jpg",
    description: "International medical school with modern approach.",
    features: ["International faculty", "Modern teaching", "Clinical exposure"],
    facilities: ["Labs", "Hospital", "Library"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 35,
    name: "Kazakh National Medical University",
    country: "kazakhstan",
    location: "Kazakhstan",
    city: "Almaty",
    tuitionFee: 5000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KAZAKHSTAN/KAZAKH.jpg",
    description: "Premier medical university with rich history.",
    features: ["Historical prestige", "Research excellence", "Clinical training"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.5,
    category: "Medical",
  },
  {
    id: 36,
    name: "South Kazakhstan Medical Academy",
    country: "kazakhstan",
    location: "Kazakhstan",
    city: "Shymkent",
    tuitionFee: 4400,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KAZAKHSTAN/SOUTHKAZAKH.jpg",
    description: "Leading medical academy in South Kazakhstan.",
    features: ["Quality education", "Modern facilities", "Clinical exposure"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 37,
    name: "University of International Business",
    country: "kazakhstan",
    location: "Kazakhstan",
    city: "Almaty",
    tuitionFee: 4700,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KAZAKHSTAN/UIB.jpg",
    description: "Modern university with international standards.",
    features: ["International collaboration", "Modern campus", "Research focus"],
    facilities: ["Research Labs", "Hospital", "Library"],
    rating: 4.3,
    category: "Medical",
  },

  // Kyrgyzstan
  {
    id: 38,
    name: "Asian Medical Institute",
    country: "kyrgyzstan",
    location: "Kyrgyzstan",
    city: "Kant",
    tuitionFee: 4000,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KYRGYZSTAN/ASIAN.jpg",
    description: "Modern medical institute with international standards.",
    features: ["Affordable", "Quality education", "Clinical training"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.1,
    category: "Medical",
  },
  {
    id: 39,
    name: "Bishkek International Medical Institute",
    country: "kyrgyzstan",
    location: "Kyrgyzstan",
    city: "Bishkek",
    tuitionFee: 4200,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KYRGYZSTAN/BISHKEK.jpg",
    description: "International medical institute in the capital city.",
    features: ["International faculty", "Modern facilities", "Clinical exposure"],
    facilities: ["Hospital", "Research Center", "Library"],
    rating: 4.2,
    category: "Medical",
  },
  {
    id: 40,
    name: "International School of Medicine",
    country: "kyrgyzstan",
    location: "Kyrgyzstan",
    city: "Bishkek",
    tuitionFee: 4300,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KYRGYZSTAN/ISM.jpg",
    description: "Leading international medical school.",
    features: ["Quality education", "Modern campus", "Clinical training"],
    facilities: ["Labs", "Hospital", "Library"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 41,
    name: "Osh State Medical University",
    country: "kyrgyzstan",
    location: "Kyrgyzstan",
    city: "Osh",
    tuitionFee: 4100,
    currency: "USD",
    duration: "6 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/KYRGYZSTAN/OSH.jpg",
    description: "Well-established medical university in Osh.",
    features: ["Affordable", "Quality education", "Clinical exposure"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.2,
    category: "Medical",
  },

  // Malaysia
  {
    id: 42,
    name: "Lincoln University College",
    country: "malaysia",
    location: "Malaysia",
    city: "Petaling Jaya",
    tuitionFee: 6000,
    currency: "USD",
    duration: "5 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/MALAYSIA/LINCOLN.jpg",
    description: "Modern medical college with international standards.",
    features: ["International recognition", "Modern facilities", "Research focus"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 43,
    name: "MAHSA University",
    country: "malaysia",
    location: "Malaysia",
    city: "Kuala Lumpur",
    tuitionFee: 6500,
    currency: "USD",
    duration: "5 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/MALAYSIA/MAHSA.jpg",
    description: "Leading private medical university in Malaysia.",
    features: ["Quality education", "Modern campus", "Clinical excellence"],
    facilities: ["Hospital", "Research Labs", "Library"],
    rating: 4.4,
    category: "Medical",
  },
  {
    id: 44,
    name: "Manipal International University",
    country: "malaysia",
    location: "Malaysia",
    city: "Nilai",
    tuitionFee: 6300,
    currency: "USD",
    duration: "5 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/MALAYSIA/MANIPAL.jpg",
    description: "International branch of renowned Manipal Group.",
    features: ["Global recognition", "Research opportunities", "Modern facilities"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.4,
    category: "Medical",
  },

  // Nepal
  {
    id: 45,
    name: "Janaki Medical College",
    country: "nepal",
    location: "Nepal",
    city: "Janakpur",
    tuitionFee: 4000,
    currency: "USD",
    duration: "5.5 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/NEPAL/JANAKI.jpg",
    description: "Established medical college with modern facilities.",
    features: ["Affordable", "Quality education", "Clinical training"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.1,
    category: "Medical",
  },
  {
    id: 46,
    name: "Kathmandu Medical College",
    country: "nepal",
    location: "Nepal",
    city: "Kathmandu",
    tuitionFee: 4500,
    currency: "USD",
    duration: "5.5 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/NEPAL/KATHMANDU.jpg",
    description: "Premier medical college in the capital city.",
    features: ["Modern facilities", "Research focus", "Clinical exposure"],
    facilities: ["Research Center", "Hospital", "Library"],
    rating: 4.3,
    category: "Medical",
  },
  {
    id: 47,
    name: "Nepalgunj Medical College",
    country: "nepal",
    location: "Nepal",
    city: "Nepalgunj",
    tuitionFee: 4200,
    currency: "USD",
    duration: "5.5 years",
    medium: "English",
    image: "/UNIVERSITY IMAGES/NEPAL/NEPALGUNJ.jpg",
    description: "Well-established medical college with comprehensive programs.",
    features: ["Quality education", "Clinical training", "Modern campus"],
    facilities: ["Hospital", "Labs", "Library"],
    rating: 4.2,
    category: "Medical",
  }
];

export default function UniversitySection() {
  const [selectedCountry, setSelectedCountry] = useState(() => {
    // Check for saved country in localStorage, default to "russia" if not found
    if (typeof window !== 'undefined') {
      const savedCountry = localStorage.getItem('selectedCountry');
      return savedCountry || "russia";
    }
    return "russia";
  });

  // Save country selection to localStorage when it changes
  const handleCountryChange = (value: string) => {
    setSelectedCountry(value);
    localStorage.setItem('selectedCountry', value);
  };

  const countries = Array.from(new Set(universities.map((uni) => uni.country)));
  const filteredUniversities = universities.filter(
    (uni) => uni.country === selectedCountry
  );

  return (
    <div className="px-4 md:px-8 py-10">
      <div className="max-w-[100vw] overflow-hidden">
        <Tabs defaultValue={selectedCountry} onValueChange={handleCountryChange}>
          <TabsList className="flex flex-wrap justify-center gap-2 mb-6 p-1 overflow-x-auto max-w-full mx-auto">
            {countries.map((country) => (
              <TabsTrigger 
                key={country} 
                value={country}
                className="whitespace-nowrap px-3 py-1.5"
              >
                {country.charAt(0).toUpperCase() + country.slice(1)}
              </TabsTrigger>
            ))}
          </TabsList>

          <TabsContent value={selectedCountry}>
            <div className="mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 max-w-6xl">
              {filteredUniversities.map((uni) => (
                <UniversityCard key={uni.id} university={uni} viewMode="grid" />
              ))}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
